import type { Metadata } from "next";
import { IBM_Plex_Sans, IBM_Plex_Mono } from "next/font/google";
import "../globals.css";
import Image from "next/image";
import { Toaster } from "sonner";
import { UserDataProvider } from "../../hooks/user-provider";

const ibmPlexSans = IBM_Plex_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
});

const ibmPlexMono = IBM_Plex_Mono({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-ibm-plex-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body
        className={`${ibmPlexSans.variable} ${ibmPlexMono.variable} antialiased`}>
        <UserDataProvider>
          <div className='w-full'>
            <div className='flex flex-col lg:flex-row'>
              {/* Image section - hidden on mobile, visible on larger screens */}
              <div className='hidden lg:block lg:w-1/2 relative h-screen'>
                <Image
                  src={"/icons/login.svg"}
                  alt='Login Image'
                  fill
                  className='object-cover'
                  priority
                />
              </div>

              {/* Content section - full width on mobile, half on larger screens */}
              <div className='w-full lg:w-1/2 flex flex-col items-center justify-center min-h-screen bg-gray-100 px-4 sm:px-6 md:px-8'>
                <div className='flex my-4'>
                  <Image
                    src='/icons/logo 1.svg'
                    alt='uhs'
                    width={50}
                    height={50}
                    className='mr-2'
                  />
                  <h1 className='text-2xl sm:text-3xl font-bold text-gray-900 mt-1.5'>
                    Urban Services
                  </h1>
                </div>
                {children}
              </div>
            </div>
          </div>
          <Toaster />
        </UserDataProvider>
      </body>
    </html>
  );
}
